spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
 eureka-provider:
  ribbon:
    ConnectTimeout: 250 #单位ms,请求连接超时时间
    ReadTimeout: 1000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
    MaxTotalConnections: 500 # 最大连接数
    MaxConnectionsPerHost: 500 # 每个host最大连接数
    retryableStatusCodes: 500,404,502 # 对Http响应码进行重试
