spring:
  application:
    name: springcloud-config-server
  port: 9005
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuwujing/springcloud-study/
          search-paths: /springcloud-config/config-repo
          username:
          password:
 # spring.application.name： 这个是指定服务名称。
 # server.port:服务指定的端口。
 # eureka.client.serviceUrl.defaultZone： 这个是设置与Eureka Server交互的地址，客户端的查询服务和注册服务都需要依赖这个地址。
 # spring.cloud.config.server.git.uri: 配置的Git长裤的地址。
 # spring.cloud.config.server.git.search-paths: git仓库地址下的相对地址 多个用逗号","分割。
 # spring.cloud.config.server.git.username:git仓库的账号。
 # spring.cloud.config.server.git.password:git仓库的密码。

  #  客户端配置
    spring:
      cloud:
        config:
          name: configtest
          profile: pro
          label: master
          discovery :
            enabled: true  #表示开启通过服务名来访问config-server
            serviceId: springcloud-config-server #表示注册中心config-server的服务名
          fail-fast: true  #启动失败时能够快速响应

            # spring.cloud.config.name： 获取配置文件的名称。
            # spring.cloud.config.profile: 获取配置的策略。
            # spring.cloud.config.label：获取配置文件的分支，默认是master。如果是是本地获取的话，则无用。
            # spring.cloud.config.discovery.enabled: 开启配置信息发现。
            # spring.cloud.config.discovery.serviceId: 指定配置中心的service-id，便于扩展为高可用配置集群。
            # eureka.client.serviceUrl.defaultZone： 这个是设置与Eureka Server交互的地址，客户端的查询服务和注册服务都需要依赖这个地址。

            #安全保护
            #spring.cloud.config.username=****
            #spring.cloud.config.password=****

            #动态刷新配置 ---需要忽略权限拦截
            #management.security.enabled=false


        #和重试机制相关的配置有如下四个：
        # 配置重试次数，默认为6
       # spring.cloud.config.retry.max-attempts=6
        # 间隔乘数，默认1.1
        #spring.cloud.config.retry.multiplier=1.1
        # 初始重试间隔时间，默认1000ms
        #spring.cloud.config.retry.initial-interval=1000
        # 最大间隔时间，默认2000ms
       # spring.cloud.config.retry.max-interval=2000





 #补充

      spring:
        cloud:
          config:
            server:
              git:
               basedir: D:\\localGitRepo\\ #更改本地仓库clone的配置文件信息的路径
            health:
              repositories:
                check:
                  name: app
                  label: master
                  profiles: prod

  #安全保护
  security:
    user:
      name:
      password:




